---
- name: Host Config Health Monior
  hosts: localhost

  #Execute before tasks
  pre_tasks:
    - set_fact:
        IC_IAM_TOKEN: "{{ lookup('env','IC_IAM_TOKEN') }}"
        IC_IAM_REFRESH_TOKEN: "{{ lookup('env','IC_IAM_REFRESH_TOKEN') }}"
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        resource_group_id: e33145f2b1294704b47c6f841c91f89c
        

- name: Host Config Health Monior
  hosts: localhost
  roles:
    - role: ../../../roles/ingress-nlb-health-monitor/nlb-host-config
      vars:
        idOrName: "mycluster-us-south-2-cx2.2x4"
        nlbHost: "mycluster-us-south-946031-b95235b88592c585af8b6e30743f88a6-0000.us-south.containers.appdomain.cloud"
