---
- name: Enable Ingress ALB 
  hosts: localhost

  #Execute before tasks
  pre_tasks:
    - set_fact:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        resource_group_id: e33145f2b1294704b47c6f841c91f89c
        

- name: Enable Ingress ALB 
  hosts: localhost
  roles:
    - role: ../../../ibm/custom_iks_collection/roles/ingress-nlb-health-monitor/nlb-health
      vars:
        clusterID: "mycluster-us-south-2-cx2.2x4"
        idOrName: "mycluster-us-south-2-cx2.2x4"
        nlbDnsType: "TCP"
        nlbHost: "mycluster-us-south-946031-b95235b88592c585af8b6e30743f88a6-0000.us-south.containers.appdomain.cloud"
        nlbIPArray: ["192.168.0.1"]
        nlbMonitorState: "enabled"
        nlbSslSecretName: "mycluster-us-south-946031-b95235b88592c585af8b6e30743f88a6-0000"
        nlbStatusMessage: "My test HTTP health monitor"
        nlbType: "TCP"
        secretNamespace: "default"