---
- name: IKS Create Config Monitoring 
  hosts: targets
  # User input variables

  #Execute before tasks
  pre_tasks:
    - set_fact:
        IC_IAM_TOKEN: "{{ lookup('env','IC_IAM_TOKEN') }}"
        IC_IAM_REFRESH_TOKEN: "{{ lookup('env','IC_IAM_REFRESH_TOKEN') }}"
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"

- name: Create Config for SysDig onitoring
  hosts: localhost
  roles:
    - role: ../../../roles/monitoring/createConfig
      vars:
        cluster: "mycluster-us-south-1-cx2.2x4"
        instance: "IBM Cloud Monitoring-ls"
