---
- name: Delete Secret
  hosts: localhost

  #Execute before tasks
  pre_tasks:
    - set_fact:
        IC_IAM_TOKEN: "{{ lookup('env','IC_IAM_TOKEN') }}"
        IC_IAM_REFRESH_TOKEN: "{{ lookup('env','IC_IAM_REFRESH_TOKEN') }}"
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        resource_group_ids: e33145f2b1294704b47c6f841c91f89c
        

- name: Delete Secret
  hosts: localhost
  roles:
    - role: ../../../roles/ingress-nlb-dns-beta/deleteSecret
      vars:
        cluster: "mycluster-us-south-2-cx2.2x4"
        subDomain: "mycluster-us-south-946031-b95235b88592c585af8b6e30743f88a6-0000.us-south.containers.appdomain.cloud"
