---
- name: IKS Custom Ansible Modules
  hosts: localhost
  # User input variables
  vars_prompt:
    - name: resource_group_id
      prompt: Enter resource_group_id

  #Execute before tasks
  pre_tasks:
    - set_fact:
        IC_IAM_TOKEN: "{{ lookup('env','IC_IAM_TOKEN') }}"
        IC_IAM_REFRESH_TOKEN: "{{ lookup('env','IC_IAM_REFRESH_TOKEN') }}"
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        resource_group_id: "{{ resource_group_id }}"
        

#- name: View cluster info
#  hosts: localhost
#  roles:
#    - role: ../roles/storage-attachment/create

#- name: Delete cluster info
#  hosts: localhost
#  roles:
#    - role: ../roles/storage-attachment/delete

- name: Create Config cluster info
  hosts: localhost
  roles:
    - role: ../../../roles/storage-attachment/delete
      vars:
        cluster: "cf63ll6d0nq35030v0u0"
        volumeAttachmentID: "sadsa-dadsad-asds-ad-as"
        worker: "kube-cf63ll6d0nq35030v0u0-myclusterus-default-00000138"