---
- ibm_container_ingress_nlb_health_monitor_info:
    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    resource_group_id: "{{ resource_group_id }}"
    config:
        clusterID: "{{clusterID}}"
        idOrName: "{{idOrName}}"
        nlbDnsType: "{{nlbDnsType}}"
        nlbHost: "{{nlbHost}}"
        nlbIPArray: "{{nlbIPArray}}"
        nlbMonitorState: "{{nlbMonitorState}}"
        nlbSslSecretName: "{{nlbSslSecretName}}"
        nlbStatusMessage: "{{nlbStatusMessage}}"
        nlbType: "{{nlbType}}"
        secretNamespace: "{{secretNamespace}}"